stages:
  - test
  - build

# Test application
test:
  only:
    - merge_request
    - tags
  stage: test
  image: golang:1.22
  script:
    - make test

# Build and publish your application in Gitlab Registry
buildAndPublish:
  image: docker:20.10.9
  stage: build
  only:
    - tags
  services:
    - docker:20.10.9-dind
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_TAG .
    - docker push $IMAGE_NAME:$CI_COMMIT_TAG
    - docker tag $IMAGE_NAME:$CI_COMMIT_TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest

