name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: make test

  build-and-publish:
    name: Build and Publish Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract Tag Name
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          docker build -t $IMAGE_NAME:${{ env.TAG }} .
          docker push $IMAGE_NAME:${{ env.TAG }}
          docker tag $IMAGE_NAME:${{ env.TAG }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest